## Example 1

In [62]:
aa = np.random.randint(0, 4, (2, 4))
print(aa)

[[2 0 3 0]
 [2 3 3 2]]


In [61]:
bb = np.random.randint(0, 10, (4, 1))
print(bb)

[[9]
 [8]
 [2]
 [0]]


### Matrix multiplication: OK

In [65]:
aa @ bb

array([[24],
       [48]])

### Elementwise product: not OK

In [ ]:
bb * aa

## Example 2

In [77]:
cc = np.random.randint(0, 6, (4, 1))
print(cc)

[[2]
 [4]
 [0]
 [5]]


In [78]:
dd = np.random.randint(0, 4, (1, 4))
print(dd)

[[0 3 1 2]]


### Matrix multiplication: OK

In [79]:
cc @ dd

array([[ 0,  6,  2,  4],
       [ 0, 12,  4,  8],
       [ 0,  0,  0,  0],
       [ 0, 15,  5, 10]])

### Matrix multiplication: OK also the other way around

In [80]:
dd @ cc

array([[22]])

### Elementwise product: also OK in both ways with the same result

In [83]:
cc * dd

array([[ 0,  6,  2,  4],
       [ 0, 12,  4,  8],
       [ 0,  0,  0,  0],
       [ 0, 15,  5, 10]])

In [84]:
dd * cc

array([[ 0,  6,  2,  4],
       [ 0, 12,  4,  8],
       [ 0,  0,  0,  0],
       [ 0, 15,  5, 10]])

## Example 3: reshaping changes the result of *

In [92]:
ee = np.random.randint(0, 4, (1, 4))
print(ee)

[[2 1 0 0]]


In [97]:
ff = np.random.randint(0, 6, (4, 1))
print(ff)

[[5]
 [5]
 [4]
 [0]]


In [98]:
print(ff.ravel())

[5 5 4 0]


In [99]:
ee * ff

array([[10,  5,  0,  0],
       [10,  5,  0,  0],
       [ 8,  4,  0,  0],
       [ 0,  0,  0,  0]])

In [100]:
ee * ff.ravel()

array([[10,  5,  0,  0]])

In [108]:
ee.reshape(4, 1) * ff

array([[10],
       [ 5],
       [ 0],
       [ 0]])