## Examples of numpy arrays

https://numpy.org/

#### 0) Import the numpy module and use a shorter namespace

In [2]:
import numpy as np

#### 1a) Print the help of **numpy.random** with help(np.random)

In [ ]:
help(np.random)

#### 1b) With shift + tab, you can display a short help of a method, such as **np.random.uniform**

In [4]:
np.random.uniform

<function RandomState.uniform>

#### 1c) Actually now the recommended way to generate pseudo random numbers is to use default_rng()

In [17]:
rng = np.random.default_rng()

In [18]:
rng

Generator(PCG64) at 0x1123C0D60

In [20]:
rng.normal(loc=1, scale=0.1, size=2)

array([1.37425677, 1.19348264])

#### 2) Create an array containing only 0s with shape (5,5)

In [5]:
array = np.zeros((5, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 3) Get the shape of this array

In [6]:
shape = array.shape
nb_lines = array.shape[0]
nb_columns = array.shape[1]
print(shape)
print(f"{nb_lines} lines")
print(f"{nb_columns} columns")

(5, 5)
5 lines
5 columns


#### 4) Fill the array with random values, uniformly distributed between -1 and 1, using a loop, using **numpy.random.uniform()**

https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html

In [7]:
for line in range(nb_lines):
    for column in range(nb_columns):
        array[line, column] = np.random.uniform(-1, 1)
print(array)

[[-0.74693355 -0.10638253  0.4649812   0.59214558  0.51838874]
 [-0.06236302  0.89470756 -0.11562676 -0.59900333 -0.59542643]
 [-0.84908841  0.65265554  0.29262484 -0.15338692  0.35807633]
 [-0.07477356 -0.46035035 -0.49171397  0.40315821 -0.16670348]
 [-0.01761602 -0.4882725   0.80710765 -0.1533598  -0.27758324]]


#### 5) Rebuild an (5,5) random array with unifomly distributed values, using only **np.random.uniform()**

In [8]:
array = np.random.uniform(-1, 1, (8, 5))
print(array)

[[ 0.57984073 -0.66444735  0.7565499  -0.35768452 -0.90102745]
 [ 0.57544169 -0.3345059  -0.65695171 -0.12565513  0.92711961]
 [-0.0713363  -0.54624702 -0.98491495 -0.65518125  0.6914869 ]
 [-0.3329462   0.23376517 -0.56209023  0.69495116 -0.08627314]
 [-0.59700109 -0.99797972 -0.7238925   0.76274489  0.68910342]
 [ 0.0661348  -0.43540481  0.68878143  0.16023813 -0.88179454]
 [-0.81913696  0.87040434 -0.05695227  0.60965913  0.84154839]
 [ 0.3961454   0.69399415  0.61213574  0.44438531 -0.26660797]]


#### 6) Transpose the array, with **numpy.transpose()**
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

In [9]:
np.transpose(array)

array([[ 0.57984073,  0.57544169, -0.0713363 , -0.3329462 , -0.59700109,
         0.0661348 , -0.81913696,  0.3961454 ],
       [-0.66444735, -0.3345059 , -0.54624702,  0.23376517, -0.99797972,
        -0.43540481,  0.87040434,  0.69399415],
       [ 0.7565499 , -0.65695171, -0.98491495, -0.56209023, -0.7238925 ,
         0.68878143, -0.05695227,  0.61213574],
       [-0.35768452, -0.12565513, -0.65518125,  0.69495116,  0.76274489,
         0.16023813,  0.60965913,  0.44438531],
       [-0.90102745,  0.92711961,  0.6914869 , -0.08627314,  0.68910342,
        -0.88179454,  0.84154839, -0.26660797]])

#### 6b) Actually it is faster to write it like that

In [10]:
array.T

array([[ 0.57984073,  0.57544169, -0.0713363 , -0.3329462 , -0.59700109,
         0.0661348 , -0.81913696,  0.3961454 ],
       [-0.66444735, -0.3345059 , -0.54624702,  0.23376517, -0.99797972,
        -0.43540481,  0.87040434,  0.69399415],
       [ 0.7565499 , -0.65695171, -0.98491495, -0.56209023, -0.7238925 ,
         0.68878143, -0.05695227,  0.61213574],
       [-0.35768452, -0.12565513, -0.65518125,  0.69495116,  0.76274489,
         0.16023813,  0.60965913,  0.44438531],
       [-0.90102745,  0.92711961,  0.6914869 , -0.08627314,  0.68910342,
        -0.88179454,  0.84154839, -0.26660797]])

#### 7) Build an boolean array, of the same shape, containing **True** if the entry of **array** is non-negative, **False** otherwise.

In [11]:
array >= 0

array([[ True, False,  True, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False,  True],
       [False,  True, False,  True, False],
       [False, False, False,  True,  True],
       [ True, False,  True,  True, False],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True, False]])

#### 8) Get the indexes where the array is positive, using **np.where()**

In [12]:
np.where(array >= 0)

(array([0, 0, 1, 1, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7]),
 array([0, 2, 0, 4, 4, 1, 3, 3, 4, 0, 2, 3, 1, 3, 4, 0, 1, 2, 3]))

#### 10) Compute the sum of the elements in the second line, using the method **numpy.sum()**

In [13]:
array[1].sum()

0.38544854966506414

#### 11) Compute the sum of the elements in all lines the keword argument "axis" 

In [14]:
array.sum(axis=0)

array([-0.20285793, -1.18042116, -0.92733459,  1.53345772,  1.01355521])

#### 13) Compute the sum of all elements in the array, with **numpy.sum()**

In [16]:
np.sum(array)

0.23639925296173914

#### 14) Check if all entries are positive, with numpy.all()

https://numpy.org/doc/stable/reference/generated/numpy.all.html

In [15]:
(array >= 0).all()

False